### ISSUE TITLE
Kodowanie

### ISSUE THREAD

**Issue by lzlocki** [Daisy1983W/webdriver#8]
https://github.com/Daisy1983W/webdriver/blob/8844bbb344f09b248ffdb3de378f52342017690b/src/test/java/RegistrationTest.java#L69

Ustawić poprawne kodowanie, polskie znaki w trakcie uruchamiania u mnie zmieniają się w krzaki. Kodowanie bezpośrednio w konfiguracji projektu (pokazywałem dla Mavena) i ewentualnie w ustawieniach narzędzia np. edycja w IntelliJ. Najlepiej UTF-8

**Comment by Daisy1983W** [comment]
A to mam zrobione w Intellij i u mnie jest poprawnie . Korzystam z Gradle nie z Mavena
